In [33]:
import pandas as pd
from utils import snowflake_login
from datetime import datetime, timedelta

In [2]:
user, cursor, snow = snowflake_login()

Intento 1
Correct Password - connected to SNOWFLAKE

In [40]:
#Aramamos listado de fechas
fechas = []
for i in range((datetime.today().replace(year=datetime.today().date().year + 1).date() -
                datetime.today().date()).days):
    fechas.append("'" + (datetime.today().date()
                         + timedelta(days=i)).strftime('%Y-%m-%d') + "'")
fechas

["'2025-10-15'",
 "'2025-10-16'",
 "'2025-10-17'",
 "'2025-10-18'",
 "'2025-10-19'",
 "'2025-10-20'",
 "'2025-10-21'",
 "'2025-10-22'",
 "'2025-10-23'",
 "'2025-10-24'",
 "'2025-10-25'",
 "'2025-10-26'",
 "'2025-10-27'",
 "'2025-10-28'",
 "'2025-10-29'",
 "'2025-10-30'",
 "'2025-10-31'",
 "'2025-11-01'",
 "'2025-11-02'",
 "'2025-11-03'",
 "'2025-11-04'",
 "'2025-11-05'",
 "'2025-11-06'",
 "'2025-11-07'",
 "'2025-11-08'",
 "'2025-11-09'",
 "'2025-11-10'",
 "'2025-11-11'",
 "'2025-11-12'",
 "'2025-11-13'",
 "'2025-11-14'",
 "'2025-11-15'",
 "'2025-11-16'",
 "'2025-11-17'",
 "'2025-11-18'",
 "'2025-11-19'",
 "'2025-11-20'",
 "'2025-11-21'",
 "'2025-11-22'",
 "'2025-11-23'",
 "'2025-11-24'",
 "'2025-11-25'",
 "'2025-11-26'",
 "'2025-11-27'",
 "'2025-11-28'",
 "'2025-11-29'",
 "'2025-11-30'",
 "'2025-12-01'",
 "'2025-12-02'",
 "'2025-12-03'",
 "'2025-12-04'",
 "'2025-12-05'",
 "'2025-12-06'",
 "'2025-12-07'",
 "'2025-12-08'",
 "'2025-12-09'",
 "'2025-12-10'",
 "'2025-12-11'",
 "'2025-12-12'",
 "'2025-12-13'",
 "'2025-12-14'",
 "'2025-12-15'",
 "'2025-12-16'",
 "'2025-12-17'",
 "'2025-12-18'",
 "'2025-12-19'",
 "'2025-12-20'",
 "'2025-12-21'",
 "'2025-12-22'",
 "'2025-12-23'",
 "'2025-12-24'",
 "'2025-12-25'",
 "'2025-12-26'",
 "'2025-12-27'",
 "'2025-12-28'",
 "'2025-12-29'",
 "'2025-12-30'",
 "'2025-12-31'",
 "'2026-01-01'",
 "'2026-01-02'",
 "'2026-01-03'",
 "'2026-01-04'",
 "'2026-01-05'",
 "'2026-01-06'",
 "'2026-01-07'",
 "'2026-01-08'",
 "'2026-01-09'",
 "'2026-01-10'",
 "'2026-01-11'",
 "'2026-01-12'",
 "'2026-01-13'",
 "'2026-01-14'",
 "'2026-01-15'",
 "'2026-01-16'",
 "'2026-01-17'",
 "'2026-01-18'",
 "'2026-01-19'",
 "'2026-01-20'",
 "'2026-01-21'",
 "'2026-01-22'",
 "'2026-01-23'",
 "'2026-01-24'",
 "'2026-01-25'",
 "'2026-01-26'",
 "'2026-01-27'",
 "'2026-01-28'",
 "'2026-01-29'",
 "'2026-01-30'",
 "'2026-01-31'",
 "'2026-02-01'",
 "'2026-02-02'",
 "'2026-02-03'",
 "'2026-02-04'",
 "'2026-02-05'",
 "'2026-02-06'",
 "'2026-02-07'",
 "'2026-02-08'",
 "'2026-02-09'",
 "'2026-02-10'",
 "'2026-02-11'",
 "'2026-02-12'",
 "'2026-02-13'",
 "'2026-02-14'",
 "'2026-02-15'",
 "'2026-02-16'",
 "'2026-02-17'",
 "'2026-02-18'",
 "'2026-02-19'",
 "'2026-02-20'",
 "'2026-02-21'",
 "'2026-02-22'",
 "'2026-02-23'",
 "'2026-02-24'",
 "'2026-02-25'",
 "'2026-02-26'",
 "'2026-02-27'",
 "'2026-02-28'",
 "'2026-03-01'",
 "'2026-03-02'",
 "'2026-03-03'",
 "'2026-03-04'",
 "'2026-03-05'",
 "'2026-03-06'",
 "'2026-03-07'",
 "'2026-03-08'",
 "'2026-03-09'",
 "'2026-03-10'",
 "'2026-03-11'",
 "'2026-03-12'",
 "'2026-03-13'",
 "'2026-03-14'",
 "'2026-03-15'",
 "'2026-03-16'",
 "'2026-03-17'",
 "'2026-03-18'",
 "'2026-03-19'",
 "'2026-03-20'",
 "'2026-03-21'",
 "'2026-03-22'",
 "'2026-03-23'",
 "'2026-03-24'",
 "'2026-03-25'",
 "'2026-03-26'",
 "'2026-03-27'",
 "'2026-03-28'",
 "'2026-03-29'",
 "'2026-03-30'",
 "'2026-03-31'",
 "'2026-04-01'",
 "'2026-04-02'",
 "'2026-04-03'",
 "'2026-04-04'",
 "'2026-04-05'",
 "'2026-04-06'",
 "'2026-04-07'",
 "'2026-04-08'",
 "'2026-04-09'",
 "'2026-04-10'",
 "'2026-04-11'",
 "'2026-04-12'",
 "'2026-04-13'",
 "'2026-04-14'",
 "'2026-04-15'",
 "'2026-04-16'",
 "'2026-04-17'",
 "'2026-04-18'",
 "'2026-04-19'",
 "'2026-04-20'",
 "'2026-04-21'",
 "'2026-04-22'",
 "'2026-04-23'",
 "'2026-04-24'",
 "'2026-04-25'",
 "'2026-04-26'",
 "'2026-04-27'",
 "'2026-04-28'",
 "'2026-04-29'",
 "'2026-04-30'",
 "'2026-05-01'",
 "'2026-05-02'",
 "'2026-05-03'",
 "'2026-05-04'",
 "'2026-05-05'",
 "'2026-05-06'",
 "'2026-05-07'",
 "'2026-05-08'",
 "'2026-05-09'",
 "'2026-05-10'",
 "'2026-05-11'",
 "'2026-05-12'",
 "'2026-05-13'",
 "'2026-05-14'",
 "'2026-05-15'",
 "'2026-05-16'",
 "'2026-05-17'",
 "'2026-05-18'",
 "'2026-05-19'",
 "'2026-05-20'",
 "'2026-05-21'",
 "'2026-05-22'",
 "'2026-05-23'",
 "'2026-05-24'",
 "'2026-05-25'",
 "'2026-05-26'",
 "'2026-05-27'",
 "'2026-05-28'",
 "'2026-05-29'",
 "'2026-05-30'",
 "'2026-05-31'",
 "'2026-06-01'",
 "'2026-06-02'",
 "'2026-06-03'",
 "'2026-06-04'",
 "'2026-06-05'",
 "'2026-06-06'",
 "'2026-06-07'",
 "'2026-06-08'",
 "'2026-06-09'",
 "'2026-06-10'",
 "'2026-06-11'",
 "'2026-06-12'",
 "'2026-06-13'",
 "'2026-06-14'",
 "'2026-06-15'",
 "'2026-06-16'",
 "'2026-06-17'",
 "'2026-06-18'",
 "'2026-06-19'",
 "'2026-06-20'",
 "'2026-06-21'",
 "'2026-06-22'",
 "'2026-06-23'",
 "'2026-06-24'",
 "'2026-06-25'",
 "'2026-06-26'",
 "'2026-06-27'",
 "'2026-06-28'",
 "'2026-06-29'",
 "'2026-06-30'",
 "'2026-07-01'",
 "'2026-07-02'",
 "'2026-07-03'",
 "'2026-07-04'",
 "'2026-07-05'",
 "'2026-07-06'",
 "'2026-07-07'",
 "'2026-07-08'",
 "'2026-07-09'",
 "'2026-07-10'",
 "'2026-07-11'",
 "'2026-07-12'",
 "'2026-07-13'",
 "'2026-07-14'",
 "'2026-07-15'",
 "'2026-07-16'",
 "'2026-07-17'",
 "'2026-07-18'",
 "'2026-07-19'",
 "'2026-07-20'",
 "'2026-07-21'",
 "'2026-07-22'",
 "'2026-07-23'",
 "'2026-07-24'",
 "'2026-07-25'",
 "'2026-07-26'",
 "'2026-07-27'",
 "'2026-07-28'",
 "'2026-07-29'",
 "'2026-07-30'",
 "'2026-07-31'",
 "'2026-08-01'",
 "'2026-08-02'",
 "'2026-08-03'",
 "'2026-08-04'",
 "'2026-08-05'",
 "'2026-08-06'",
 "'2026-08-07'",
 "'2026-08-08'",
 "'2026-08-09'",
 "'2026-08-10'",
 "'2026-08-11'",
 "'2026-08-12'",
 "'2026-08-13'",
 "'2026-08-14'",
 "'2026-08-15'",
 "'2026-08-16'",
 "'2026-08-17'",
 "'2026-08-18'",
 "'2026-08-19'",
 "'2026-08-20'",
 "'2026-08-21'",
 "'2026-08-22'",
 "'2026-08-23'",
 "'2026-08-24'",
 "'2026-08-25'",
 "'2026-08-26'",
 "'2026-08-27'",
 "'2026-08-28'",
 "'2026-08-29'",
 "'2026-08-30'",
 "'2026-08-31'",
 "'2026-09-01'",
 "'2026-09-02'",
 "'2026-09-03'",
 "'2026-09-04'",
 "'2026-09-05'",
 "'2026-09-06'",
 "'2026-09-07'",
 "'2026-09-08'",
 "'2026-09-09'",
 "'2026-09-10'",
 "'2026-09-11'",
 "'2026-09-12'",
 "'2026-09-13'",
 "'2026-09-14'",
 "'2026-09-15'",
 "'2026-09-16'",
 "'2026-09-17'",
 "'2026-09-18'",
 "'2026-09-19'",
 "'2026-09-20'",
 "'2026-09-21'",
 "'2026-09-22'",
 "'2026-09-23'",
 "'2026-09-24'",
 "'2026-09-25'",
 "'2026-09-26'",
 "'2026-09-27'",
 "'2026-09-28'",
 "'2026-09-29'",
 "'2026-09-30'",
 "'2026-10-01'",
 "'2026-10-02'",
 "'2026-10-03'",
 "'2026-10-04'",
 "'2026-10-05'",
 "'2026-10-06'",
 "'2026-10-07'",
 "'2026-10-08'",
 "'2026-10-09'",
 "'2026-10-10'",
 "'2026-10-11'",
 "'2026-10-12'",
 "'2026-10-13'",
 "'2026-10-14'"]

In [49]:
if datetime.strptime(fechas[0].strip("'"), "%Y-%m-%d") < datetime.strptime(fechas[1].strip("'"), "%Y-%m-%d"):
    print(fechas[0], fechas[1])

'2025-10-15' '2025-10-16'

In [26]:
evento = pd.read_excel('Evento Zafra comestibles.xlsx')
evento.columns = evento.columns.str.upper()
evento.columns = evento.columns.str.strip()
evento

          ITEM                                        DESCRIPCIÓN
0   1000053284                BUDÍN MARMOLADO PORTEZUELO 200 GRS.
1   1000053286                BUDÍN GRANIZADO PORTEZUELO 200 GRS.
2   1000053289    PAN DULCE RELLENO CHOCOLATE PORTEZUELO 450.00 G
3   1000053291          BUDÍN EXTRA GRANIZADO PORTEZUELO 200 GRS.
4   1000053292          BUDÍN SÚPER CHOCOLATE PORTEZUELO 240 GRS.
5   1000053293   PAN DULCE RELLENO DULCE DE L PORTEZUELO 450.00 G
6   1000053316                      PAN DULCE PORTEZUELO 400.00 G
7   1000053322     PAN DULCE CHOCOLATTO PORTEZUELO BOLSA 400.00 G
8   1000053326            BUDÍN DULCE DE LECHE GRANIZADO 240 GRS.
9   1000053328   BUDÍN BLACK MEGA RELLENO DULCE DE LECHE 240 GRS.
10  1000413353            PAN DULCE RELLENO DE CHOCOLATE TATA 350
11  1000413354                  PAN DULCE RELLENO DE DDL TATA 350
12  1000574765              BUDIN DON VALENTIN GRANIZADO 150 GRS.
13  1000574766            PAN DE MASA DULCE DON VALENTIN 400 GRS.
14  1000574767              BUDIN DON VALENTIN MARMOLADO 150 GRS.
15  1000574769             BUDIN DON VALENTIN CON FRUTAS 150 GRS.
16  1000347599                      BUDIN 9 DE ORO VAINILLA 170 G
17  1000347600                     BUDIN 9 DE ORO MARMOLADO 170 G
18  1000347601  BUDIN 9 DE ORO VAINILLA RELLENO DULCE DE LECHE...
19  1000347602                     BUDIN 9 DE ORO CHOCOLATE 170 G

In [27]:
cols = {'ITEM':'ORIN', 'LOCAL':'GEOG_LOCL_COD', 'LOCALES':'GEOG_LOCL_COD'}

In [28]:
evento.rename(columns=cols, inplace=True)

In [29]:
evento.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ORIN         20 non-null     int64
 1   DESCRIPCIÓN  20 non-null     object
dtypes: int64(1), object(1)
memory usage: 452.0+ bytes

In [30]:
if 'GEOG_LOCL_COD' in evento.columns:
    evento = evento[['ORIN', 'GEOG_LOCL_COD']].drop_duplicates().astype('str')
else:
    evento = evento[['ORIN']].drop_duplicates()
    evento['aux'] = 1
    locales = pd.read_excel('LOCALES.xlsx')
    locales['aux'] = 1
    evento = evento.merge(locales).drop(columns='aux').astype('str')
evento

            ORIN GEOG_LOCL_COD
0     1000053284           198
1     1000053284           480
2     1000053284           482
3     1000053284           483
4     1000053284           484
...          ...           ...
2215  1000347602           412
2216  1000347602           417
2217  1000347602           418
2218  1000347602           419
2219  1000347602           420

[2220 rows x 2 columns]

In [ ]:
cursor.execute('SELECT ARTC_ARTC_COD, ORIN FROM MSTRDB.DWH.LU_ARTC_ARTICULO;')
art = cursor.fetch_pandas_all().astype('str')
art

OperationalError: 254007: The certificate is revoked or could not be validated: hostname=sfc-va-ds1-5-customer-stage.s3.amazonaws.com

In [19]:
art.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302041 entries, 0 to 302040
Data columns (total 2 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   ARTC_ARTC_COD  302041 non-null  object
 1   ORIN           271635 non-null  object
dtypes: object(2)
memory usage: 4.6+ MB

In [ ]:
evento = evento.merge(art)
evento

       GEOG_LOCL_COD        ORIN ARTC_ARTC_COD
0                101  1000555474     220915000
1                101  1000555248     220733000
2                101  1000150181     220872600
3                101  1000555906     221173000
4                101  1000555905     221172000
...              ...         ...           ...
14208            331  1000047316     221802000
14209            334  1000479841     220457000
14210            334  1000047316     221802000
14211            335  1000479841     220457000
14212            335  1000047316     221802000

[14213 rows x 3 columns]

In [21]:
evento['PROM_FECHA_INICIO'] = '2025-09-29'
evento['PROM_FECHA_INICIO'] = pd.to_datetime(evento['PROM_FECHA_INICIO'])
evento['PROM_FECHA_FIN'] = '2025-10-03'
evento['PROM_FECHA_FIN'] = pd.to_datetime(evento['PROM_FECHA_FIN'])
evento['EVENTO_ID'] = 2547
evento['PRONOSTICO_VENTA'] = 0
evento['STOCK_INICIAL_PROMO'] = 0
evento['PROM_PVP_OFERTA'] = 0
evento['PROM_LOCAL_ACTIVO'] = 0
evento['PROM_ESTIBA'] = 0
evento

,GEOG_LOCL_COD,ORIN,ARTC_ARTC_COD,PROM_FECHA_INICIO,PROM_FECHA_FIN,EVENTO_ID,PRONOSTICO_VENTA,STOCK_INICIAL_PROMO,PROM_PVP_OFERTA,PROM_LOCAL_ACTIVO,PROM_ESTIBA
0,101,1000555474,220915000,2025-09-29,2025-10-03,2547,0,0,0,0,0
1,101,1000555248,220733000,2025-09-29,2025-10-03,2547,0,0,0,0,0
2,101,1000150181,220872600,2025-09-29,2025-10-03,2547,0,0,0,0,0
3,101,1000555906,221173000,2025-09-29,2025-10-03,2547,0,0,0,0,0
4,101,1000555905,221172000,2025-09-29,2025-10-03,2547,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
14208,331,1000047316,221802000,2025-09-29,2025-10-03,2547,0,0,0,0,0
14209,334,1000479841,220457000,2025-09-29,2025-10-03,2547,0,0,0,0,0
14210,334,1000047316,221802000,2025-09-29,2025-10-03,2547,0,0,0,0,0
14211,335,1000479841,220457000,2025-09-29,2025-10-03,2547,0,0,0,0,0
14212,335,1000047316,221802000,2025-09-29,2025-10-03,2547,0,0,0,0,0

In [22]:
evento.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14213 entries, 0 to 14212
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   GEOG_LOCL_COD        14213 non-null  int64
 1   ORIN                 14213 non-null  object
 2   ARTC_ARTC_COD        14213 non-null  object
 3   PROM_FECHA_INICIO    14213 non-null  datetime64[ns]
 4   PROM_FECHA_FIN       14213 non-null  datetime64[ns]
 5   EVENTO_ID            14213 non-null  int64
 6   PRONOSTICO_VENTA     14213 non-null  int64
 7   STOCK_INICIAL_PROMO  14213 non-null  int64
 8   PROM_PVP_OFERTA      14213 non-null  int64
 9   PROM_LOCAL_ACTIVO    14213 non-null  int64
 10  PROM_ESTIBA          14213 non-null  int64
dtypes: datetime64[ns](2), int64(7), object(2)
memory usage: 1.2+ MB

In [23]:
evento_final = evento[['PROM_FECHA_INICIO', 'PROM_FECHA_FIN', 'ARTC_ARTC_COD', 'EVENTO_ID', 'PRONOSTICO_VENTA',
                       'STOCK_INICIAL_PROMO', 'GEOG_LOCL_COD', 'PROM_PVP_OFERTA', 'PROM_LOCAL_ACTIVO', 'PROM_ESTIBA',
                       'ORIN']].astype({'ARTC_ARTC_COD':'str', 'GEOG_LOCL_COD':'str', 'ORIN':'str'})
evento_final

,PROM_FECHA_INICIO,PROM_FECHA_FIN,ARTC_ARTC_COD,EVENTO_ID,PRONOSTICO_VENTA,STOCK_INICIAL_PROMO,GEOG_LOCL_COD,PROM_PVP_OFERTA,PROM_LOCAL_ACTIVO,PROM_ESTIBA,ORIN
0,2025-09-29,2025-10-03,220915000,2547,0,0,101,0,0,0,1000555474
1,2025-09-29,2025-10-03,220733000,2547,0,0,101,0,0,0,1000555248
2,2025-09-29,2025-10-03,220872600,2547,0,0,101,0,0,0,1000150181
3,2025-09-29,2025-10-03,221173000,2547,0,0,101,0,0,0,1000555906
4,2025-09-29,2025-10-03,221172000,2547,0,0,101,0,0,0,1000555905
...,...,...,...,...,...,...,...,...,...,...,...
14208,2025-09-29,2025-10-03,221802000,2547,0,0,331,0,0,0,1000047316
14209,2025-09-29,2025-10-03,220457000,2547,0,0,334,0,0,0,1000479841
14210,2025-09-29,2025-10-03,221802000,2547,0,0,334,0,0,0,1000047316
14211,2025-09-29,2025-10-03,220457000,2547,0,0,335,0,0,0,1000479841
14212,2025-09-29,2025-10-03,221802000,2547,0,0,335,0,0,0,1000047316

In [24]:
evento_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14213 entries, 0 to 14212
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   PROM_FECHA_INICIO    14213 non-null  datetime64[ns]
 1   PROM_FECHA_FIN       14213 non-null  datetime64[ns]
 2   ARTC_ARTC_COD        14213 non-null  object
 3   EVENTO_ID            14213 non-null  int64
 4   PRONOSTICO_VENTA     14213 non-null  int64
 5   STOCK_INICIAL_PROMO  14213 non-null  int64
 6   GEOG_LOCL_COD        14213 non-null  object
 7   PROM_PVP_OFERTA      14213 non-null  int64
 8   PROM_LOCAL_ACTIVO    14213 non-null  int64
 9   PROM_ESTIBA          14213 non-null  int64
 10  ORIN                 14213 non-null  object
dtypes: datetime64[ns](2), int64(6), object(3)
memory usage: 1.2+ MB

In [25]:
evento_final.to_csv('G:/Unidades compartidas/Inteligencia de Negocio/Promos/Eventos adhoc/Evento adhoc.csv')